server:
  servlet:
    context-path: "/payment"
  port: 8183


integration:
  user-product:
    url: "http://localhost:8181"
    connect-timeout: 5s
    read-timeout: 5s

spring:
  application:
    name: payment-core
  datasource:
    url: jdbc:postgresql://localhost:5428/postgres_db
    username: postgres_user
    password: postgres_password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none